exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7530da50>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://bc586039.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752939b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://8f5694e0.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75308a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://d8c9acd3.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752baa30>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://e7d1a21d.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752c7a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://3f21fb7f.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752f9a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://786a1d78.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7656b490>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://c4b623d5.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752f8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://cfb80ef5.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75233a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://93976390.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75262a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://28550e99.ngrok.io
ngrok created  https://20a8a526.ngrok.io
exception HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75320a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
ngrok created  https://80b99468.ngrok.io
